-- MySQL Script generated by MySQL Workbench
-- Sun Sep 15 20:42:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_veterinaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_veterinaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_veterinaria` DEFAULT CHARACTER SET utf8 ;
USE `db_veterinaria` ;

-- -----------------------------------------------------
-- Table `db_veterinaria`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`ROL` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rolId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_USUARIO_ROL_idx` (`rolId` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_ROL`
    FOREIGN KEY (`rolId`)
    REFERENCES `db_veterinaria`.`ROL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`CLIENTE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `usuarioId` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_CLIENTES_USUARIO1_idx` (`usuarioId` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTES_USUARIO1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `db_veterinaria`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`VETERINARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`VETERINARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `usuarioId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_VETERINARIO_USUARIO1_idx` (`usuarioId` ASC) VISIBLE,
  CONSTRAINT `fk_VETERINARIO_USUARIO1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `db_veterinaria`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`MASCOTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`MASCOTA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `peso` DOUBLE NOT NULL,
  `raza` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  `clienteId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MASCOTA_CLIENTE1_idx` (`clienteId` ASC) VISIBLE,
  CONSTRAINT `fk_MASCOTA_CLIENTE1`
    FOREIGN KEY (`clienteId`)
    REFERENCES `db_veterinaria`.`CLIENTE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`PROGRAMACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`PROGRAMACION` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `horaInicio` VARCHAR(45) NOT NULL,
  `horaFin` VARCHAR(45) NOT NULL,
  `activo` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`HORARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`HORARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `programacionId` INT NOT NULL DEFAULT 1,
  `veterinarioId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_HORARIO_PROGRAMACION1_idx` (`programacionId` ASC) VISIBLE,
  INDEX `fk_HORARIO_VETERINARIO1_idx` (`veterinarioId` ASC) VISIBLE,
  CONSTRAINT `fk_HORARIO_PROGRAMACION1`
    FOREIGN KEY (`programacionId`)
    REFERENCES `db_veterinaria`.`PROGRAMACION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HORARIO_VETERINARIO1`
    FOREIGN KEY (`veterinarioId`)
    REFERENCES `db_veterinaria`.`VETERINARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`CITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`CITA` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mascotaId` INT NOT NULL,
  `veterinarioId` INT NOT NULL,
  `horarioId` INT NOT NULL,
  `cancelado` INT NOT NULL DEFAULT 0,
  `fechaRegistr` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CITA_VETERINARIO1_idx` (`veterinarioId` ASC) VISIBLE,
  INDEX `fk_CITA_HORARIO1_idx` (`horarioId` ASC) VISIBLE,
  INDEX `fk_CITA_MASCOTA1_idx` (`mascotaId` ASC) VISIBLE,
  CONSTRAINT `fk_CITA_VETERINARIO1`
    FOREIGN KEY (`veterinarioId`)
    REFERENCES `db_veterinaria`.`VETERINARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_HORARIO1`
    FOREIGN KEY (`horarioId`)
    REFERENCES `db_veterinaria`.`HORARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_MASCOTA1`
    FOREIGN KEY (`mascotaId`)
    REFERENCES `db_veterinaria`.`MASCOTA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_veterinaria`.`HISTORIALCLINICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_veterinaria`.`HISTORIALCLINICO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `receta` VARCHAR(500) NULL,
  `observaciones` VARCHAR(500) NULL,
  `mascotaId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_HISTORIALCLINICO_MASCOTA1_idx` (`mascotaId` ASC) VISIBLE,
  CONSTRAINT `fk_HISTORIALCLINICO_MASCOTA1`
    FOREIGN KEY (`mascotaId`)
    REFERENCES `db_veterinaria`.`MASCOTA` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
